Page({
  data:{
    btnc:false,
    btnd:false,
    btne:false,
    btnf:false,
    btng:false,
    btna:false,
    btnb:false,
    src:'images/c.png'
  },
  c(){
    this.setData({
      btnc:true,
      btnd:false,
      btne:false,
      btnf:false,
      btng:false,
      btna:false,
      btnb:false,
    })
  },
  d(){
    this.setData({
      btnc:false,
      btnd:true,
      btne:false,
      btnf:false,
      btng:false,
      btna:false,
      btnb:false,
    })
  },
  e(){
    this.setData({
      btnc:false,
      btnd:false,
      btne:true,
      btnf:false,
      btng:false,
      btna:false,
      btnb:false,
    })
  },
  f(){
    this.setData({
      btnc:false,
      btnd:false,
      btne:false,
      btnf:true,
      btng:false,
      btna:false,
      btnb:false,
    })
  },
  g(){
    this.setData({
      btnc:false,
      btnd:false,
      btne:false,
      btnf:false,
      btng:true,
      btna:false,
      btnb:false,
    })
  },
  a(){
    this.setData({
      btnc:false,
      btnd:false,
      btne:false,
      btnf:false,
      btng:false,
      btna:true,
      btnb:false,
    })
  },
  b(){
    this.setData({
      btnc:false,
      btnd:false,
      btne:false,
      btnf:false,
      btng:false,
      btna:false,
      btnb:true,
    })
  },
})